name: Say Hello

on:
  pull_request:
    types: [opened, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_target:
    types: [synchronize, converted_to_draft, ready_for_review, review_requested, review_request_removed]

jobs:
  run-my-action:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: 'needs-review'
